name: Build and Test

on:
  push:
    branches:
      - main
      - develop  # You can also use feature branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd services/auth-service
        npm install
        cd ../user-service
        npm install
        cd ..

    - name: Build Docker images
      run: |
        docker build -t your-dockerhub-username/auth-service services/auth-service
        docker build -t your-dockerhub-username/user-service services/user-service

    - name: Run tests
      run: |
        cd services/auth-service
        npm test
        cd ../user-service
        npm test
        cd ..

    - name: Push Docker images
      if: success()
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push muralidharan2705/microservices-devops-project-user-service
        docker push muralidharan2705/microservices-devops-project-auth-service
